/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "SlbBase.h"

SlbBase::SlbBase(const std::string name) {
  logger()->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [Slb] [%n] [%l] %v");
}



SlbBase::~SlbBase() {}

void SlbBase::update(const SlbJsonObject &conf) {
  set_conf(conf.getBase());

  if (conf.channelLocIsSet()) {
    setChannelLoc(conf.getChannelLoc());
  }
  if (conf.channelLenIsSet()) {
    setChannelLen(conf.getChannelLen());
  }
  if (conf.ingressActionIsSet()) {
    setIngressAction(conf.getIngressAction());
  }
  if (conf.egressActionIsSet()) {
    setEgressAction(conf.getEgressAction());
  }
}

SlbJsonObject SlbBase::toJsonObject() {
  SlbJsonObject conf;
  conf.setBase(to_json());

  conf.setName(getName());
  conf.setChannelLoc(getChannelLoc());
  conf.setChannelLen(getChannelLen());
  conf.setIngressAction(getIngressAction());
  conf.setEgressAction(getEgressAction());

  return conf;
}


