/*
 * slb API
 *
 * slb API generated from slb.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Slb struct {
	// Name of the slb service
	Name string `json:"name,omitempty"`
	// UUID of the Cube
	Uuid string `json:"uuid,omitempty"`
	// Type of the Cube (TC, XDP_SKB, XDP_DRV)
	Type_ string `json:"type,omitempty"`
	ServiceName string `json:"service-name,omitempty"`
	// Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
	Loglevel string `json:"loglevel,omitempty"`
	// where the channel info located? Default is LSB.
	ChannelLoc string `json:"channel-loc,omitempty"`
	// number of bits used for channel
	ChannelLen int32 `json:"channel-len,omitempty"`
	// server id
	ServerId int32 `json:"server-id,omitempty"`
	// Action performed on ingress packets
	IngressAction string `json:"ingress-action,omitempty"`
	// Action performed on egress packets
	EgressAction string `json:"egress-action,omitempty"`
}
