/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SlbApiImpl.h
*
*
*/

#pragma once


#include <memory>
#include <map>
#include <mutex>
#include "../Slb.h"

#include "SlbJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace SlbApiImpl {
  void create_slb_by_id(const std::string &name, const SlbJsonObject &value);
  void delete_slb_by_id(const std::string &name);
  SlbJsonObject read_slb_by_id(const std::string &name);
  uint8_t read_slb_channel_len_by_id(const std::string &name);
  SlbChannelLocEnum read_slb_channel_loc_by_id(const std::string &name);
  std::vector<SlbJsonObject> read_slb_list_by_id();
  void replace_slb_by_id(const std::string &name, const SlbJsonObject &value);
  void update_slb_by_id(const std::string &name, const SlbJsonObject &value);
  void update_slb_channel_len_by_id(const std::string &name, const uint8_t &value);
  void update_slb_channel_loc_by_id(const std::string &name, const SlbChannelLocEnum &value);
  void update_slb_list_by_id(const std::vector<SlbJsonObject> &value);

  /* help related */
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_slb_list_by_id_get_list();

}
}
}
}

