/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SlbApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "slb"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "SlbJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_slb_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_slb_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_channel_len_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_channel_loc_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_egress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_ingress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_slb_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_slb_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_channel_len_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_channel_loc_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_egress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_ingress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_slb_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response slb_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

