/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SlbJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "polycube/services/cube.h"

namespace polycube {
namespace service {
namespace model {

enum class SlbChannelLocEnum {
  MSB, LSB
};
enum class SlbIngressActionEnum {
  DROP, PASS, SLOWPATH
};
enum class SlbEgressActionEnum {
  DROP, PASS, SLOWPATH, SLB
};

/// <summary>
///
/// </summary>
class  SlbJsonObject : public JsonObjectBase {
public:
  SlbJsonObject();
  SlbJsonObject(const nlohmann::json &json);
  ~SlbJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Name of the slb service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// where the channel info located? Default is LSB.
  /// </summary>
  SlbChannelLocEnum getChannelLoc() const;
  void setChannelLoc(SlbChannelLocEnum value);
  bool channelLocIsSet() const;
  void unsetChannelLoc();
  static std::string SlbChannelLocEnum_to_string(const SlbChannelLocEnum &value);
  static SlbChannelLocEnum string_to_SlbChannelLocEnum(const std::string &str);

  /// <summary>
  /// number of bits used for channel
  /// </summary>
  uint8_t getChannelLen() const;
  void setChannelLen(uint8_t value);
  bool channelLenIsSet() const;
  void unsetChannelLen();

  /// <summary>
  /// server id
  /// </summary>
  uint16_t getServerId() const;
  void setServerId(uint16_t value);
  bool serverIdIsSet() const;
  void unsetServerId();

  /// <summary>
  /// Action performed on ingress packets
  /// </summary>
  SlbIngressActionEnum getIngressAction() const;
  void setIngressAction(SlbIngressActionEnum value);
  bool ingressActionIsSet() const;
  void unsetIngressAction();
  static std::string SlbIngressActionEnum_to_string(const SlbIngressActionEnum &value);
  static SlbIngressActionEnum string_to_SlbIngressActionEnum(const std::string &str);

  /// <summary>
  /// Action performed on egress packets
  /// </summary>
  SlbEgressActionEnum getEgressAction() const;
  void setEgressAction(SlbEgressActionEnum value);
  bool egressActionIsSet() const;
  void unsetEgressAction();
  static std::string SlbEgressActionEnum_to_string(const SlbEgressActionEnum &value);
  static SlbEgressActionEnum string_to_SlbEgressActionEnum(const std::string &str);

private:
  std::string m_name;
  bool m_nameIsSet;
  SlbChannelLocEnum m_channelLoc;
  bool m_channelLocIsSet;
  uint8_t m_channelLen;
  bool m_channelLenIsSet;
  uint16_t m_serverId;
  bool m_serverIdIsSet;
  SlbIngressActionEnum m_ingressAction;
  bool m_ingressActionIsSet;
  SlbEgressActionEnum m_egressAction;
  bool m_egressActionIsSet;
};

}
}
}

