/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/SlbApiImpl.h"
#include "../datamodel/slb.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "HEAD/159c099"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return slb_datamodel.c_str();
}
