/**
* slb API generated from slb.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "Slb.h"
#include "Slb_dp.h"

Slb::Slb(const std::string name, const SlbJsonObject &conf)
  : TransparentCube(conf.getBase(), { slb_code }, {}),
    SlbBase(name) {
  logger()->info("Creating Slb instance");
  if (conf.channelLocIsSet()) {
    setChannelLoc(conf.getChannelLoc());
  }

  if (conf.channelLenIsSet()) {
    setChannelLen(conf.getChannelLen());
  }

}


Slb::~Slb() {
  logger()->info("Destroying Slb instance");
}

void Slb::packet_in(polycube::service::Sense sense,
    polycube::service::PacketInMetadata &md,
    const std::vector<uint8_t> &packet) {
    logger()->debug("Packet received");
}

SlbChannelLocEnum Slb::getChannelLoc() {
  throw std::runtime_error("Slb::getChannelLoc: Method not implemented");
}

void Slb::setChannelLoc(const SlbChannelLocEnum &value) {
  throw std::runtime_error("Slb::setChannelLoc: Method not implemented");
}

uint8_t Slb::getChannelLen() {
  throw std::runtime_error("Slb::getChannelLen: Method not implemented");
}

void Slb::setChannelLen(const uint8_t &value) {
  throw std::runtime_error("Slb::setChannelLen: Method not implemented");
}


